# Introdução ao Numpy

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(lista, type(lista))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] <class 'list'>


In [3]:
array = np.array(lista)
print(array, type(array))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [4]:
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
array[0]

1

In [6]:
array[0] = 11
array[0]

11

In [7]:
array_2d = np.zeros((5, 3))
array_2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
lista_notas = [9.8, 5.6, 7.8, 9.1, 6.5]
lista_notas

[9.8, 5.6, 7.8, 9.1, 6.5]

In [9]:
lista_notas  = np.array(lista_notas)
lista_notas

array([9.8, 5.6, 7.8, 9.1, 6.5])

In [10]:
lista_notas.max()

9.8

In [11]:
lista_notas.min()

5.6

In [12]:
lista_notas.mean()

7.76

In [13]:
lista_notas.std()

1.5628179676469045

In [14]:
lista_notas.argmax()

0

In [15]:
lista_notas.argmin()

1